server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
  config:
    import:
      - classpath:/application-datasource.yml
      - classpath:/application-oauth2.yml

logging:
  level:
    root: info
    sql: debug