spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 448150452984-6mpfngbg95slvnoc5dg19k0qu9nivf4q.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile